### ISSUE TITLE
rigidBody.tex - 3.6.2 Coordinate Transformation Example - equation error

### ISSUE THREAD

**Issue by Napester** [gaoxiang12/slambook-en#13]
... The answer to the program is [-0:0309731; 0:73499; 0:296108]T, and the calculation
process is very simple, just by calculating
`$$ \mathbf{p}_{R_2} = \mathbf{T}_{ R_2, W} \mathbf{T}_{W, R_1} \mathbf{p}_{R_1}. $$`
should be:
`$$ \mathbf{p}_{R_2} = \mathbf{T}_{ R_2, W} \mathbf{T}_{W, R_1}^{-1} \mathbf{p}_{R_1}. $$`
(inverse operator is missing)

**Comment by gaoxiang12** [comment]
Hi @Napester ,
Please note that by $$ \mathbf{T}_{ R_2, W} \mathbf{T}_{W, R_1} \mathbf{p}_{R_1} $$ we first convert p_{R_1} from R_1 to the World, then from the World to R_2. The equation should be read from right to left, so it is right.

**Comment by Napester** [comment]
Thanks for clarification, I misread it.
