### ISSUE TITLE
Chapter 4, Lie Groups and Lie Algebra

### ISSUE THREAD

**Issue by nicolasrosa** [gaoxiang12/slambook-en#22]
Hello @gaoxiang12

I'm reading chapter 4 and I got a little confused about the definitions of <img src="https://render.githubusercontent.com/render/math?math=\phi(t).">

First, you said that this variable is a 3D vector, <img src="https://render.githubusercontent.com/render/math?math=\phi(t) \in \mathbb{R}^3">, and that its skew-symmetric matrix is: <img src="https://render.githubusercontent.com/render/math?math=\mathbf{\dot{R}}(t)\mathbf{R}(t)^{T} = \phi(t)\hat{}">

Second, you said "We see that <img src="https://render.githubusercontent.com/render/math?math=\phi"> reflects the derivative of **R**, so it is called the **Tangent Space** near the origin of SO(3)". Are you refering to <img src="https://render.githubusercontent.com/render/math?math=\phi(t)"> or <img src="https://render.githubusercontent.com/render/math?math=\phi(t_0)">? The second one, right?

Third, you said that "The previously mentioned <img src="https://render.githubusercontent.com/render/math?math=\phi"> is actually a kind of Lie algebra.". I think this sentence is a little misleading since the presented definiton of Lie Algebra was <img src="https://render.githubusercontent.com/render/math?math=\mathfrak{g}=(\mathbb{V}, \mathbb{F}, [,])">, and the <img src="https://render.githubusercontent.com/render/math?math=\phi"> presented so far is just a 3D vector.

I believe the notation for Lie Algebra <img src="https://render.githubusercontent.com/render/math?math=\mathfrak{so}(3)"> should be <img src="https://render.githubusercontent.com/render/math?math=\mathfrak{so}(3)=(\mathbb{R}^3, \mathbb{R}?, \Phi')">, where <img src="https://render.githubusercontent.com/render/math?math=\Phi' = [\phi_1, \phi_2]=(\Phi_1 \Phi_2 - \Phi_2 \Phi_1)\check{}=(\phi_1\hat{} \phi_2\hat{} - \phi_2\hat{} \phi_1\hat{})\check{}"> is the Lie bracket/Arithmetic Operator. Am I right?

In the equation 4.13, how is possible the <img src="https://render.githubusercontent.com/render/math?math=\mathfrak{so}(3)"> also include <img src="https://render.githubusercontent.com/render/math?math=\mathbb{R}^{3x3}"> values, if the arithmetic operator contains the "<img src="https://render.githubusercontent.com/render/math?math=\check{}">" (Skew-Symmetric Matrix back to Vector) ?

This way, I believe the equation 4.13 should be changed to <img src="https://render.githubusercontent.com/render/math?math=\mathbb{V}_{\mathfrak{so}(3)} = \{ \phi \in \mathbb{R}^3\}">.

Considering everything said, analyzing a beforementioned sentence "you will find that they are exactly the correspondence between Lie Group and Lie Algebra". In our case:
Lie Group: <img src="https://render.githubusercontent.com/render/math?math=\mathbf{R} \in SO(3)">
Lie Algebra: <img src="https://render.githubusercontent.com/render/math?math=\mathfrak{so}(3)=(\phi \in \mathbb{R}^3, \mathbb{R}?, \Phi')">

So, is the <img src="https://render.githubusercontent.com/render/math?math=\phi"> the AngleAxis <img src="https://render.githubusercontent.com/render/math?math=\theta\vec{\mathbf{n}}"> presented in the topic 3.3.1 Rotation Vector? <img src="https://render.githubusercontent.com/render/math?math=\vec{\mathbf{a}}"> presented in section 4.2.1 is the <img src="https://render.githubusercontent.com/render/math?math=\vec{\mathbf{n}}">, right?

**Comment by gaoxiang12** [comment]
Hi @nicolasrosa, in my opinion, the vector \phi to skew-symmetric matrix \Phi is a one-by-one relationship, so it would be ok to write so(3) either in vector or matrix form. Given an arbitrary 3D vector \phi we can find one (and only one) corresponding \Phi, and vise versa. I agree that write it in the matrix form is better for understanding and consistency. 

There is a general definition of Lie groups and Lie algebra, and SO3/so3 is just a special instance of that. In some books, people may start from the generalized definition but we start from an example. In 4.1.2 I just want to naturally introduce the definition of Lie algebra so I use a somewhat less strict way by solving the ODE say '\phi(t) keeps equal to \phi (t_0) in a short time' and then give a solution to that.  

The last sentence is right. 

Sorry I don't know how to type latex in this github box. Please let me know if anything is still not clear.

**Comment by nicolasrosa** [comment]
Hello @gaoxiang12,

After getting used to the one-to-one relationship, I understood the relaxation in the notations. Thank you.

I have another question, in formula 4.41, which property did you use to pass from the first equation to the second one?

![CodeCogsEqn](https://user-images.githubusercontent.com/7122146/102395016-5b686500-3fb9-11eb-8304-68e22c6d3bf4.gif)

Did you use the Skew-Symmetric and Cross Product relationship?

![CodeCogsEqn (1)](https://user-images.githubusercontent.com/7122146/102397130-3b867080-3fbc-11eb-8d90-6d09f708fad1.gif)

---
Obs.: I was using this website [https://latex.codecogs.com/eqneditor/editor.php](https://latex.codecogs.com/eqneditor/editor.php)
for typing the equations and later I just paste the equations here using the following code:

`<img src="https://render.githubusercontent.com/render/math?math=MATH_LATEX_HERE">`

**Comment by gaoxiang12** [comment]
Yes exactly. It is just a basic property of the cross product.
