### ISSUE TITLE
Chapter 4, Exercise 7

### ISSUE THREAD

**Issue by nicolasrosa** [gaoxiang12/slambook-en#24]
Hello @gaoxiang12,
Could you give me a hint about the following exercise?

7. Follow the derivation of the left perturbation and derives the derivatives of SO(3) and SE(3) under the right perturbation.

**SO(3)** - Left Perturbation (![CodeCogsEqn](https://user-images.githubusercontent.com/7122146/104743880-f5dbd580-572a-11eb-8e26-50d5839c5c2b.gif), ![CodeCogsEqn (4)](https://user-images.githubusercontent.com/7122146/104744405-9af6ae00-572b-11eb-83eb-2fa0deb286f0.gif))
![image](https://user-images.githubusercontent.com/7122146/104743503-882fa980-572a-11eb-9acf-8e1e2e4cf409.png)

**SE(3)** - Left Perturbation (![CodeCogsEqn (1)](https://user-images.githubusercontent.com/7122146/104744135-47846000-572b-11eb-994f-b97a49432c71.gif))
![image](https://user-images.githubusercontent.com/7122146/104743562-98478900-572a-11eb-835f-676d433ef8d8.png)

**SO(3)** - Right Perturbation (![CodeCogsEqn (3)](https://user-images.githubusercontent.com/7122146/104744152-4eab6e00-572b-11eb-987d-c1740b944f4b.gif))
???

**SE(3)** - Right Perturbation (![CodeCogsEqn (2)](https://user-images.githubusercontent.com/7122146/104744166-55d27c00-572b-11eb-83f8-bf57a2b1a085.gif))
???

**Comment by gaoxiang12** [comment]
Hi @nicolasrosa 
The right perturbation model is just similar to the left model. The perturbation is performed on the right side of the rotation/transform matrix and then approximated by Taylor expansion: 
![image](https://user-images.githubusercontent.com/6635511/106411523-76673980-6480-11eb-8024-52a98e6d80de.png)

The SE(3) model is almost the same so I just omit it here.

**Comment by nicolasrosa** [comment]
Oh, I see the difference now. Thank you!
