### ISSUE TITLE
clarification needed

### ISSUE THREAD

**Issue by jonassvedas** [gaoxiang12/slambook-en#29]
Section 3.12, equation 3.5. It is not made clear why when multiplying both sides of the equation by the transpose of the unit vector e, the coefficient on the left becomes a identity matrix.

**Comment by nicolasrosa** [comment]
![CodeCogsEqn](https://user-images.githubusercontent.com/7122146/109672337-b0952b00-7b53-11eb-9a8e-8d7f572fef28.gif)

![image](https://user-images.githubusercontent.com/7122146/109672442-cd316300-7b53-11eb-9bda-ccc81e04f664.png)

**Comment by jonassvedas** [comment]
Thanks that makes it clear.
Also what is not mentioned in the book is what is **e1,e2,e3**. My assumption is that if **e** is a unit vector than **e1,e2,e3** are the vector components in the direction of each axis. E.g. if **e** = (a,b,c) then **e1** = (a,0,0) ,**e2** = (0,b,0) , **e3** = (0,0,c)?

**Comment by nicolasrosa** [comment]
I believe the sentence "We have a unit-length orthogonal base (e1; e2; e3)" was presented to get the concept of what you just said. Maybe @gaoxiang12 can present this in a more clear way.

**Comment by jonassvedas** [comment]
Yeah that is not very clear what that is, because the sentance has e1,e2,e3 in bold which is the notation for a vector, right? So is my assumption that [**e1,e2,e3**] is a diagonal matrix with the values on the diagonal corresponding to the coordinates of **e**?

**Comment by gaoxiang12** [comment]
Hi @jonassvedas, the e1,e2,e3 are just vectors here, without coordinates.

We can compute the plus, minus, inner product and outer product of the vectors without using the coordinates (also without defining any coordinate systems). The result of the inner product is the multiplication of their length and the angle. If the coordinates are known, it is the same as the sum of the product of the coordinates.

So [e1, e2, e3] here is not a diagonal matrix, but just a row of vectors. They follow the matrix multiplication rules when doing multiplication as @nicolasrosa writes. In some book, it is called the _vertrix_ but we don't introduce this concept in our book.

**Comment by nicolasrosa** [comment]
@jonassvedas Can we close this issue?
