### ISSUE TITLE
SubScript of State Estimation Equation

### ISSUE THREAD

**Issue by sumitsarkar1** [gaoxiang12/slambook-en#30]
In equation 9.4 , its written P(x_k | x_0 , u_1:k , z_1:k ). Will it be P(x_k | x_0 : k-1 , u_1:k , z_1:k ) because the next following line its written "The subscript 0 : k represents all the data from time 0 to time k" . However we dont see a subscript 0 : k. Please kindly clarify. I am sorry if I am being silly and missing out something obvious.

**Comment by gaoxiang12** [comment]
Ah, thanks for pointing it out. I changed this text from 0:k to 1:k now. We don't assume x_0:k-1 is conditionally known when estimating x_k, so it would be better to change the text after this equation.

**Comment by sumitsarkar1** [comment]
Just to clarify : Is this intuition correct that since the states evolve increamentally from x_0 to x_{k-1} and then x_{k} ,  x_{k} is deep down dependent on x_0. Markov assumption makes x_{k} dependent on x_{k-1} (which later you explain in 9.6) but to start with in 9.4 you propose in P(x_k | x_0 , u_1:k , z_1:k ) that x_{k} is dependent on only on x_0, u_1:k and z_1:k . In short what makes you assume x_0:k-1 is not known conditionally when estimating x_k

**Comment by gaoxiang12** [comment]
Yes exactly. Without assuming the Markov property, we can only write the pdf as P(x_k | x_0 , u_1:k , z_1:k ). But if we assume x_k is only affected by x_k-1, then we can put the x_k-1 into the condition part to compute the conditional distribution.

**Comment by sumitsarkar1** [comment]
@gaoxiang12 thanx a lot Sir....your book is amazing !!
