### ISSUE TITLE
ZYX is ypr

### ISSUE THREAD

**Issue by dimaxano** [gaoxiang12/slambook-en#33]
Hi!
I found a mistake on [this](https://github.com/gaoxiang12/slambook-en/blob/82dedb5b04ded816ce44eb6ff404b9235bfca03a/chapters/rigidBody.tex#L468) line, I think
ZYX is Yaw-Pitch-Roll (ypr) not Roll-Pitch-Yaw (rpy)

**Comment by gaoxiang12** [comment]
Fixed. Thank you for your careful reading!

**Comment by dimaxano** [comment]
This is the least I can do to pay you back for this amazing book!

Also similar typo [here](https://github.com/gaoxiang12/slambook-en/blob/ecc8424af3e4fc629aa6e9b5251833c3381d43c7/chapters/rigidBody.tex#L472) btw
`the rotation order of the rpy angle is ZYX` should be XYZ
And then later in this passage in the sentence `Similarly, there are Euler angles like XYZ..` XYZ should be replaced with some other combination
