### ISSUE TITLE
Trajectory representation

### ISSUE THREAD

**Issue by dimaxano** [gaoxiang12/slambook-en#36]
Hi!
Explanation about trajectory representation (from [here](https://github.com/gaoxiang12/slambook-en/blob/2af7394fd701e656c41b8dd155ff93184b316552/chapters/rigidBody.tex#L888)) still not clear for me.
Am I right that `O_R` always equal to (0,0,0), because this is the origin of a robot in the robot coordinate frame?

**Comment by gaoxiang12** [comment]
@dimaxano Yes, O_R is always zero, so when left multiplied by T_WR, the result will be R_WR * 0 + t_WR = t_WR.
