### ISSUE TITLE
[Ch7] Equation 7.34

### ISSUE THREAD

**Issue by nicolasrosa** [gaoxiang12/slambook-en#38]
@gaoxiang12 

Is equation 7.34 correct?

I think it should be:

![CodeCogsEqn](https://user-images.githubusercontent.com/7122146/111655032-0fab9e80-87e8-11eb-823c-b2ac2705d5da.gif)

**Comment by gaoxiang12** [comment]
I think you are correct. Thank you for your careful reading!
