### ISSUE TITLE
Duplicate text

### ISSUE THREAD

**Issue by lhruby** [gaoxiang12/slambook-en#43]
Chapter 9, page 240, following eq. 9.12, the text from above the equation appears a second time.

> After understanding the Jacobian derivation, the rest is the same as ordinary
graph optimization. In short, all pose vertices and pose edges constitute a graph
optimization, which is essentially a least-squares problem. The optimization variable
is the pose of each vertex, and the edges come from the pose observation constraints.
Let E be the set of all edges, then the overall objective function is

**Comment by gaoxiang12** [comment]
Thanks, fixed in the recent commit.
