### ISSUE TITLE
Rephrasing needed (maybe)

### ISSUE THREAD

**Issue by abougouffa** [gaoxiang12/slambook-en#46]
First, I would like to thank you for this book, it is really a very good resource in the subject.

I didn't understand this phrase (in chapter 5, p105)

![Screenshot_20210616_181043](https://user-images.githubusercontent.com/3716399/122255457-6a7b9180-cece-11eb-8123-73d4076a539f.png)

- ***s is the distance of pixels*** ?! do you mean the **depth**, the **size**, or the **scaling factor**?
- What do you mean by ***the third element of ...***

https://github.com/gaoxiang12/slambook-en/blob/ba3a4e2072d31a0bc3a2ee3e15c0ffacba468674/chapters/nonlinearOptimization.tex#L37

**Comment by gaoxiang12** [comment]
Hi @abougouffa ,
- s is the real distance of the pixel. i.e. the distance from the 3D point to the image plane, sometimes it is also mentioned as the scale. Please check the pinhole model in chapter 4 (equation 4.8). 
![image](https://user-images.githubusercontent.com/6635511/122319355-1b2b7480-cf53-11eb-873b-5da93e42992a.png)

The symbols are slightly different but the meaning is the same.

On the left side of (5.2), s is a scalar, and z_{k,j} is a 3D vector like [u,v,1]^T. When multiplying them together, we get a vector [su, sv, s]^T.
One the right side, K(Ry+t) also gives a 3D vector. By comparing them, we see s is exactly the third element of K(Ry+t).
