### ISSUE TITLE
Ch1 Picture in Chinese 

### ISSUE THREAD

**Issue by swershrimpy** [gaoxiang12/slambook-en#47]
Hi Dr Gao,
Thank you very much for the book! This book is well written and is helping me tremendously with learning more basic robotics and SLAM concepts for my research. I noticed, however, that a few figures in Chapter 1 are in Chinese, which may make it harder for non Chinese speakers to understand the material. I can re-generate those pictures using my own device and upload the images/ change the .tex myself.  May I do that?

**Comment by gaoxiang12** [comment]
Hi @swershrimpy , thanks for your attention! I've just remade these figures yesterday using an English ubuntu environment. Now it looks like below:
![image](https://user-images.githubusercontent.com/6635511/123031332-bc647000-d416-11eb-88f6-2b5c2bc8d9f8.png)

**Comment by swershrimpy** [comment]
Thanks for the reply! I realized the book was updated just an hour ago and I didn't get the latest version
