### ISSUE TITLE
Translation of the rats of the book.

### ISSUE THREAD

**Issue by mzahana** [gaoxiang12/slambook-en#9]
Thanks @gaoxiang12 for the great effort. I can see only chapters 1 and 2 translated to English.  Is the rest of the book translated to English?

**Comment by gaoxiang12** [comment]
Sorry I haven't get the other chapters translated for now and I'll probably do it after writing the second edition of this book, should be the end of 2018.

**Comment by mzahana** [comment]
Thank you
